spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      database: studentrating
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: graphql/*.graphqls
server:
  port: 4203