graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: graphql/*.graphqls
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: studentrating
server:
  port: 8099
